# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: be39e27c0d4845c43a39e714b95a163dfdd032d8e6900fe6965fbe1d208d429fc09a6a22598b517ceedac9e967141e63776460f519a53d6ef0b1b7ea85184651

test:
  secret_key_base: 67aaad8d9f6d8ecf445bdf7643292f34e31d0ffaada440d3b7b38b78a0440a1db8a363456005f9a02f5f123f51d304f7237acf4d5e73e9718d65bcbd5944af4c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
